(function () {
  'use strict';
  const C=window.LiveCutEditCore,$=(s,r=document)=>r.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const time=n=>`${Math.floor(n/60)}:${(n%60).toFixed(2).padStart(5,'0')}`;
  const s={p:null,tid:null,selected:null,undo:[],redo:[],time:0,playing:false,zoom:70,nodes:new Map(),root:null,
    frame:0,timer:null,poll:null,saving:null,dirty:false,styles:{}};
  const tl=()=>s.p?.timelines.find(t=>t.id===s.tid),asset=id=>s.p.assets.find(a=>a.id===id);
  const url=a=>`/api/editor/projects/${s.p.id}/assets/${a.id}`;
  const total=()=>Math.max(0,...tl().tracks.filter(t=>!t.hidden).flatMap(t=>t.clips.map(C.end)));
  const find=id=>{for(const t of tl()?.tracks||[]){const c=t.clips.find(c=>c.id===id);if(c)return {t,c};}return {};};
  async function req(path,method='GET',data){const r=await fetch('/api/editor/'+path,{method,headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error||'请求失败');return d;}
  function msg(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),3500);}
  function ask(title,value='',multiline=false){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='modal';dialog.innerHTML=`<form class="modal-body"><h2>${esc(title)}</h2><label for="editorPromptValue">${esc(title)}</label>${multiline?'<textarea id="editorPromptValue" rows="4"></textarea>':'<input id="editorPromptValue">'}<div class="editor-actions"><button class="button primary" id="editorPromptConfirm" type="submit">确定</button><button class="button ghost" id="editorPromptCancel" type="button">取消</button></div></form>`;document.body.append(dialog);const input=dialog.querySelector('#editorPromptValue');input.value=value;dialog.querySelector('form').onsubmit=e=>{e.preventDefault();dialog.close('ok');};dialog.querySelector('#editorPromptCancel').onclick=()=>dialog.close();dialog.onclose=()=>{resolve(dialog.returnValue==='ok'?input.value:null);dialog.remove();};dialog.showModal();input.focus();input.select();});}
  function change(){s.dirty=true;clearTimeout(s.timer);s.timer=setTimeout(()=>save().catch(e=>msg(e.message)),800);rows();properties();}
  function edit(fn){const before=C.clone(s.p);try{s.undo.push(before);if(s.undo.length>80)s.undo.shift();s.redo=[];fn();change();}catch(e){s.p=before;s.undo.pop();rows();properties();msg(e.message);}}
  async function save(){
    clearTimeout(s.timer);if(s.saving){await s.saving;if(s.dirty)return save();return;}if(!s.dirty)return;
    const p=C.clone(s.p),fingerprint=JSON.stringify(p);$('#editorSaveState')?.replaceChildren(document.createTextNode('保存中…'));
    s.saving=req('projects/'+p.id,'PUT',p);
    try{const saved=await s.saving;s.p.revision=saved.revision;s.dirty=JSON.stringify({...s.p,revision:p.revision})!==fingerprint;
      $('#editorSaveState')?.replaceChildren(document.createTextNode(s.dirty?'仍有未保存编辑':'已保存'));
      if(s.dirty)s.timer=setTimeout(()=>save().catch(e=>msg(e.message)),800);
    }catch(e){s.dirty=true;$('#editorSaveState')?.replaceChildren(document.createTextNode('保存失败：'+e.message));throw e;}finally{s.saving=null;}
  }
  function history(redo=false){const src=redo?s.redo:s.undo,dst=redo?s.undo:s.redo;if(!src.length)return;
    const revision=s.p.revision,assets=s.p.assets;dst.push(C.clone(s.p));s.p=src.pop();s.p.revision=revision;s.p.assets=assets;
    if(!tl())s.tid=s.p.timelines[0].id;s.selected=null;tabs();change();}
  function cleanup(){s.playing=false;cancelAnimationFrame(s.frame);clearTimeout(s.poll);for(const n of s.nodes.values()){n.pause?.();n.removeAttribute('src');n.load?.();}s.nodes.clear();}
  async function list(root){const d=await req('projects');root.innerHTML=`<div class="hero"><div><h1>人工剪辑</h1><p>多时间线、多轨剪辑、字幕与音乐，完成后自动导出。</p></div><div class="editor-actions"><button class="button ghost" id="importV1">从 V1 成片创建</button><button class="button primary" id="newEdit">新建项目</button></div></div><div class="editor-projects">${d.projects.map(p=>`<button class="panel editor-project" data-project="${p.id}"><b>${esc(p.title)}</b><span>${p.timeline_count} 条时间线 · ${new Date(p.updated*1000).toLocaleString()}</span></button>`).join('')||'<div class="panel">新建项目导入视频，或直接选择 V1 成片。</div>'}</div><div id="exportList" class="panel"></div>`;
    $('#newEdit').onclick=async()=>{const title=await ask('项目名称','人工精剪');if(title===null)return;try{const p=await req('projects','POST',{title});location.hash='#/editor/'+p.id;}catch(e){msg(e.message);}};
    for(const b of root.querySelectorAll('[data-project]'))b.onclick=()=>location.hash='#/editor/'+b.dataset.project;$('#importV1').onclick=()=>importV1().catch(e=>msg(e.message));poll();}
  async function importV1(){const data=await fetch('/api/jobs').then(r=>r.json()),jobs=data.jobs.filter(j=>j.status==='completed');
    const dialog=document.createElement('dialog');dialog.className='modal';dialog.innerHTML=`<div class="modal-body"><h2>选择 V1 成片任务</h2><select id="v1Job">${jobs.map(j=>`<option value="${j.id}">${esc(j.title)}</option>`).join('')}</select><p>保留来源关联；原素材与原任务不修改。</p><button class="button primary" id="v1Import">创建项目</button><button class="button ghost" id="v1Close">取消</button></div>`;
    document.body.append(dialog);dialog.showModal();$('#v1Close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
    $('#v1Import').onclick=async()=>{try{const id=$('#v1Job').value;if(!id)throw new Error('没有已完成的任务');const j=await fetch('/api/jobs/'+id).then(r=>r.json());
      const paths=[...new Set((j.artifacts||[]).filter(a=>a.kind==='video'&&a.path.endsWith('.mp4')&&a.path.includes('deliverables')).map(a=>a.path))];
      if(!paths.length)throw new Error('任务没有可导入的成片');let p=await req('projects','POST',{title:j.title+' 精剪',source_job_id:id});
      for(const path of paths){const r=await req(`projects/${p.id}/assets`,'POST',{path});p=r.project;C.addClip(p.timelines[0].tracks[0],r.asset,Math.max(0,...p.timelines[0].tracks[0].clips.map(C.end)));p=await req('projects/'+p.id,'PUT',p);}
      dialog.close();location.hash='#/editor/'+p.id;
    }catch(e){msg(e.message);}};
  }
  function layout(){const p=s.p;s.root.innerHTML=`<div class="editor-head"><a href="#/editor" class="button ghost small">项目列表</a><input id="projectTitle" aria-label="项目名称" value="${esc(p.title)}"><span id="editorSaveState">已保存</span><button class="button ghost small" id="saveEdit">保存</button><button class="button primary small" id="exportEdit">导出当前时间线</button></div>
    <div class="editor-workspace"><section class="panel editor-bin"><div class="panel-head"><h2>素材库</h2><button class="button ghost small" id="addMedia">导入</button></div><input id="assetSearch" placeholder="搜索素材"><div id="assetList"></div></section>
    <section class="panel editor-monitor"><div class="editor-stage"><canvas id="editCanvas" width="${p.width}" height="${p.height}"></canvas></div><div class="editor-transport"><button class="button ghost small" id="playEdit">播放 / 空格</button><button class="button ghost small" id="frameBack">◀ 帧</button><button class="button ghost small" id="frameNext">帧 ▶</button><span id="editClock">0:00.00</span><input type="range" id="editSeek" min="0" max="1" step="0.001" value="0" aria-label="播放位置"></div><small>基础效果实时预览；导出后请核对字幕排版和动态素材。</small></section>
    <section class="panel editor-properties"><div class="panel-head"><h2>片段属性</h2></div><div id="clipProperties"></div></section></div>
    <section class="panel editor-timeline"><div id="timelineTabs" class="editor-tabs"></div><div class="editor-toolbar"><button data-action="split">分割 S</button><button data-action="delete">删除</button><button data-action="ripple">波纹删除</button><button data-action="copy">复制片段</button><button data-action="detach">分离音频</button><button data-action="undo">撤销</button><button data-action="redo">重做</button><select id="newTrackKind"><option value="video">视频轨</option><option value="audio">音频轨</option><option value="image">贴纸轨</option><option value="subtitle">字幕轨</option></select><button id="addTrack">添加轨道</button><button id="addSubtitle">添加字幕</button><button id="importSubtitle">导入 SRT</button><button id="recognizeSubtitle">识别选中片段字幕</button><label>缩放 <input type="range" id="timelineZoom" min="15" max="180" value="${s.zoom}"></label></div><div class="editor-scroll"><div id="timelineRows"></div></div></section>
    <section class="panel editor-export"><div class="panel-head"><h2>导出与后处理</h2><a href="#/settings/editor">输出设置</a></div><div class="editor-post"><label><input id="postProgress" type="checkbox" ${p.postprocess.progress?'checked':''}> 底部 6 像素进度条（缩小画面留边）</label><label>画中画 <select id="postPip"><option value="">不添加</option>${p.assets.filter(a=>a.kind!=='audio').map(a=>`<option value="${a.id}" ${p.postprocess.pip_asset===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>不透明度 <input id="postOpacity" type="number" min="0" max="100" step=".1" value="${p.postprocess.pip_opacity*100}"> %</label><label>角落贴纸 <select id="postSticker"><option value="">不添加</option>${p.assets.filter(a=>a.kind==='image').map(a=>`<option value="${a.id}" ${p.postprocess.sticker_asset===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label></div><div id="exportList"></div></section>`;
    $('#projectTitle').onchange=e=>edit(()=>s.p.title=e.target.value);$('#saveEdit').onclick=()=>save().then(()=>msg('已保存')).catch(e=>msg(e.message));
    $('#exportEdit').onclick=async()=>{try{await save();await req(`projects/${p.id}/export`,'POST',{revision:s.p.revision,timeline_id:s.tid});msg('已加入导出队列');poll();}catch(e){msg(e.message);}};
    $('#addMedia').onclick=()=>importMedia().catch(e=>msg(e.message));$('#assetSearch').oninput=assets;
    $('#playEdit').onclick=play;$('#frameBack').onclick=()=>seek(s.time-1/p.fps);$('#frameNext').onclick=()=>seek(s.time+1/p.fps);$('#editSeek').oninput=e=>seek(Number(e.target.value));
    $('#addTrack').onclick=()=>edit(()=>tl().tracks.push({id:C.id(),name:$('#newTrackKind').selectedOptions[0].textContent,kind:$('#newTrackKind').value,clips:[]}));
    $('#addSubtitle').onclick=async()=>{const text=await ask('字幕文字','');if(text)edit(()=>{let t=tl().tracks.find(t=>t.kind==='subtitle'&&!t.locked);if(!t){t={id:C.id(),name:'字幕',kind:'subtitle',clips:[]};tl().tracks.push(t);}const c={id:C.id(),start:s.time,duration:3,in:0,speed:1,text,style:'classic',font_size:56};t.clips.push(c);s.selected=c.id;});};
    $('#importSubtitle').onclick=importSrt;$('#recognizeSubtitle').onclick=recognize;$('#timelineZoom').oninput=e=>{s.zoom=Number(e.target.value);rows();};for(const b of s.root.querySelectorAll('[data-action]'))b.onclick=()=>action(b.dataset.action);
    for(const [selector,key,type] of [['#postProgress','progress','checked'],['#postPip','pip_asset','value'],['#postSticker','sticker_asset','value'],['#postOpacity','pip_opacity','value']])$(selector).onchange=e=>edit(()=>s.p.postprocess[key]=key==='pip_opacity'?Number(e.target.value)/100:e.target[type]);
    tabs();assets();rows();properties();poll();tick();
  }
  function tabs(){const el=$('#timelineTabs');if(!el)return;el.innerHTML=s.p.timelines.map(t=>`<button class="tab-button ${t.id===s.tid?'active':''}" data-timeline="${t.id}">${esc(t.name)}</button>`).join('')+'<button id="newTimeline">＋ 时间线</button><button id="copyTimeline">复制时间线</button><button id="renameTimeline">重命名</button>';
    for(const b of el.querySelectorAll('[data-timeline]'))b.onclick=()=>{cleanup();s.tid=b.dataset.timeline;s.selected=null;s.time=0;tabs();rows();properties();poll();tick();};
    $('#newTimeline').onclick=()=>{edit(()=>{const t=C.duplicateTimeline(s.p.timelines[0]);t.name='时间线'+String(s.p.timelines.length+1).padStart(2,'0');for(const track of t.tracks)track.clips=[];s.p.timelines.push(t);s.tid=t.id;s.time=0;});tabs();};
    $('#copyTimeline').onclick=()=>{edit(()=>{const t=C.duplicateTimeline(tl());s.p.timelines.push(t);s.tid=t.id;});tabs();};
    $('#renameTimeline').onclick=async()=>{const name=await ask('时间线名称',tl().name);if(name){edit(()=>tl().name=name);tabs();}};
  }
  async function importMedia(){await save();let paths;if(window.livecutDesktop)paths=await window.livecutDesktop.pickFiles();else{const path=await ask('粘贴本地素材绝对路径（多个路径每行一个）','',true);paths=path?path.split(/\r?\n/).filter(Boolean):[];}
    for(const path of paths){const r=await req(`projects/${s.p.id}/assets`,'POST',{path});s.p=r.project;}cleanup();layout();}
  function assets(){const el=$('#assetList');if(!el)return;const q=$('#assetSearch').value.toLowerCase();el.innerHTML=s.p.assets.filter(a=>a.name.toLowerCase().includes(q)).map(a=>`<article class="editor-asset" draggable="true" data-asset="${a.id}">${a.kind!=='audio'?`<img loading="lazy" src="${url(a)}/thumbnail" alt="">`:'<span class="editor-audio-icon">♫</span>'}<b>${esc(a.name)}</b><small>${a.kind==='image'?'贴纸 / 图片':time(a.duration)}</small><button class="button ghost small" data-add="${a.id}">加入时间线</button></article>`).join('')||'<p>导入视频、音乐或贴纸，拖动素材到轨道。</p>';
    for(const a of el.querySelectorAll('[data-asset]'))a.ondragstart=e=>e.dataTransfer.setData('application/livecut-asset',a.dataset.asset);
    for(const b of el.querySelectorAll('[data-add]'))b.onclick=()=>edit(()=>{const a=asset(b.dataset.add);let t=tl().tracks.find(t=>!t.locked&&t.kind===a.kind);if(!t){t={id:C.id(),name:a.kind,kind:a.kind,clips:[]};tl().tracks.push(t);}s.selected=C.addClip(t,a,Math.max(0,...t.clips.map(C.end))).id;});}
  const waves=new Map();
  async function wave(a,canvas,c){try{if(!waves.has(a.id))waves.set(a.id,fetch(url(a)+'/waveform').then(r=>r.json()).then(d=>d.peaks));const peaks=await waves.get(a.id);if(!canvas.isConnected||!peaks?.length)return;canvas.width=Math.min(800,canvas.clientWidth||100);const ctx=canvas.getContext('2d');ctx.strokeStyle='#8ce7da';ctx.beginPath();for(let i=0;i<canvas.width;i++){const sec=(c.in||0)+(i/canvas.width)*c.duration*(c.speed||1),v=Math.min(1,peaks[Math.floor(sec/a.duration*peaks.length)]||0)*10;ctx.moveTo(i,10-v);ctx.lineTo(i,10+v);}ctx.stroke();}catch{}}
  function rows(){const el=$('#timelineRows');if(!el)return;const length=Math.max(15,total()+3),width=length*s.zoom,marks=Array.from({length:Math.ceil(length/5)},(_,i)=>`<span style="left:${i*5*s.zoom}px">${time(i*5)}</span>`).join('');el.style.width=width+150+'px';
    el.innerHTML=`<div class="editor-ruler"><div class="editor-track-label">时间</div><div class="editor-lane ruler" style="width:${width}px">${marks}</div></div>`+tl().tracks.map(t=>`<div class="editor-track"><div class="editor-track-label"><b>${esc(t.name)}</b><div><button data-track="${t.id}" data-toggle="hidden" title="显示 / 隐藏">${t.hidden?'○':'◉'}</button><button data-track="${t.id}" data-toggle="muted" title="静音">${t.muted?'静':'声'}</button><button data-track="${t.id}" data-toggle="locked" title="锁定">${t.locked?'锁':'开'}</button></div></div><div class="editor-lane ${esc(t.kind)}" data-track="${t.id}" style="width:${width}px">${t.clips.map(c=>`<div class="edit-clip ${c.id===s.selected?'selected':''}" tabindex="0" data-clip="${c.id}" style="left:${c.start*s.zoom}px;width:${Math.max(4,c.duration*s.zoom)}px"><i data-trim="left"></i><span>${esc(c.text||asset(c.asset_id)?.name||'素材缺失')}</span><small>${time(c.duration)}</small>${t.kind==='audio'||t.kind==='video'?'<canvas class="clip-wave" height="20"></canvas>':''}<i data-trim="right"></i></div>`).join('')}</div></div>`).join('')+`<div id="editorPlayhead" style="left:${150+s.time*s.zoom}px"></div>`;
    for(const b of el.querySelectorAll('[data-toggle]'))b.onclick=()=>edit(()=>{const t=tl().tracks.find(t=>t.id===b.dataset.track);t[b.dataset.toggle]=!t[b.dataset.toggle];});
    for(const lane of el.querySelectorAll('.editor-lane')){lane.onclick=e=>{if(!e.target.closest('[data-clip]'))seek((e.clientX-lane.getBoundingClientRect().left)/s.zoom);};lane.ondragover=e=>e.preventDefault();lane.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('application/livecut-asset');if(id&&lane.dataset.track)edit(()=>{const t=tl().tracks.find(t=>t.id===lane.dataset.track);s.selected=C.addClip(t,asset(id),(e.clientX-lane.getBoundingClientRect().left)/s.zoom).id;});};}
    for(const el of document.querySelectorAll('[data-clip]')){el.onpointerdown=e=>drag(e,el);const {c}=find(el.dataset.clip),a=asset(c.asset_id),canvas=el.querySelector('canvas');if(canvas&&a?.has_audio)wave(a,canvas,c);}
  }
  function drag(e,el){if(e.button!==0)return;e.preventDefault();const {t,c}=find(el.dataset.clip);s.selected=c.id;properties();for(const x of document.querySelectorAll('.edit-clip'))x.classList.toggle('selected',x.dataset.clip===c.id);if(t.locked)return;
    const before=C.clone(s.p),initial={...c},x=e.clientX,trim=e.target.dataset.trim;
    const move=ev=>{let d=Math.round((ev.clientX-x)/s.zoom*s.p.fps)/s.p.fps;
      if(trim==='left'){d=Math.max(-initial.start,-(initial.in||0)/(initial.speed||1),Math.min(d,initial.duration-1/s.p.fps));c.start=initial.start+d;c.in=(initial.in||0)+d*(initial.speed||1);c.duration=initial.duration-d;}
      else if(trim==='right'){const a=asset(c.asset_id),max=a&&a.kind!=='image'?(a.duration-(c.in||0))/(c.speed||1):86400;c.duration=Math.max(1/s.p.fps,Math.min(max,initial.duration+d));}
      else{let next=Math.max(0,initial.start+d);for(const b of [s.time,...t.clips.filter(v=>v.id!==c.id).flatMap(v=>[v.start,C.end(v)])])if(Math.abs(next-b)*s.zoom<7){next=b;break;}c.start=next;}
      el.style.left=c.start*s.zoom+'px';el.style.width=Math.max(4,c.duration*s.zoom)+'px';};
    const up=()=>{window.removeEventListener('pointermove',move);if(JSON.stringify(before)!==JSON.stringify(s.p)){s.undo.push(before);s.redo=[];change();}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
  function action(name){if(name==='undo'||name==='redo')return history(name==='redo');const {t,c}=find(s.selected);if(!c)return msg('先选择片段');edit(()=>{if(t.locked)throw new Error('轨道已锁定');
    if(name==='split')C.split(t,c.id,s.time,s.p.fps);if(name==='delete'){t.clips=t.clips.filter(x=>x.id!==c.id);s.selected=null;}if(name==='ripple'){C.rippleDelete(tl(),t,c.id);s.selected=null;}
    if(name==='copy'){const n={...C.clone(c),id:C.id(),start:C.end(c)};t.clips.push(n);s.selected=n.id;}
    if(name==='detach'){if(t.kind!=='video'||!asset(c.asset_id)?.has_audio)throw new Error('选择带声音的视频片段');let target=tl().tracks.find(t=>t.kind==='audio'&&!t.locked);if(!target){target={id:C.id(),name:'原声',kind:'audio',clips:[]};tl().tracks.push(target);}target.clips.push({...C.clone(c),id:C.id(),muted:false});c.muted=true;}
  });}
  function properties(){const el=$('#clipProperties');if(!el)return;const {t,c}=find(s.selected);if(!c){el.innerHTML='<p>选择片段以调整属性。字幕可改字、换模板、调整时间。</p>';return;}
    const f=(label,key,value,min,max,step='.01')=>`<label>${label}<input data-property="${key}" type="number" step="${step}" min="${min}" max="${max}" value="${value}"></label>`;
    const opts=(map,key)=>Object.entries(map).map(([v,l])=>`<option value="${v}" ${(c[key]||'none')===v?'selected':''}>${l}</option>`).join('');
    el.innerHTML=`<b>${esc(t.name)}</b>${f('开始（秒）','start',c.start,0,86400)}${f('时长（秒）','duration',c.duration,1/s.p.fps,86400)}${t.kind==='subtitle'?`<label>字幕文字<textarea data-property="text">${esc(c.text)}</textarea></label><label>模板<select data-property="style">${Object.entries(s.styles).map(([k,v])=>`<option value="${k}" ${(c.style||'classic')===k?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label>${f('字号','font_size',c.font_size||56,12,240,'1')}`:`${f('素材入点','in',c.in||0,0,86400)}${f('倍速','speed',c.speed||1,.25,4)}${f('音量','volume',c.volume??1,0,4)}<label><input data-property="muted" type="checkbox" ${c.muted?'checked':''}> 静音</label>${f('声音淡入','fade_in',c.fade_in||0,0,10)}${f('声音淡出','fade_out',c.fade_out||0,0,10)}`}
    ${t.kind!=='audio'?`${f('不透明度（0–1）','opacity',c.opacity??1,0,1)}${f('横向偏移比例','x',c.x||0,-2,2)}${f('纵向偏移比例','y',c.y||0,-2,2)}${t.kind!=='subtitle'?`${f('宽度比例','scale',c.scale??1,.01,3)}${f('旋转角度','rotation',c.rotation||0,-360,360,'1')}<label>特效<select data-property="effect">${opts({none:'无',warm:'暖色',cool:'冷色',mono:'黑白',blur:'模糊'},'effect')}</select></label><label>入场 / 转场<select data-property="transition">${opts({none:'无',fade:'叠化',slide:'滑入',wipe:'擦除'},'transition')}</select></label>${f('转场时长','transition_duration',c.transition_duration??.3,0,5)}<button id="overlapTransition">与前段重叠形成转场</button>`:''}`:''}`;
    for(const input of el.querySelectorAll('[data-property]'))input.onchange=()=>edit(()=>{if(t.locked)throw new Error('轨道已锁定');const key=input.dataset.property,value=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;if(input.type==='number'&&(!Number.isFinite(value)||value<Number(input.min)||value>Number(input.max)))throw new Error('数值超出范围');if(key==='speed')c.duration=c.duration*(c.speed||1)/value;else if(['duration','in'].includes(key)&&t.kind!=='subtitle'){const a=asset(c.asset_id);if(a.kind!=='image'&&(key==='in'?value+c.duration*(c.speed||1):(c.in||0)+value*(c.speed||1))>a.duration+.001)throw new Error('超出素材时长');}c[key]=value;});
    $('#overlapTransition')?.addEventListener('click',()=>edit(()=>{if(t.locked)throw new Error('轨道已锁定');const sorted=[...t.clips].sort((a,b)=>a.start-b.start),prev=sorted[sorted.indexOf(c)-1];if(!prev)throw new Error('没有前一个片段');c.start=Math.max(prev.start,C.end(prev)-Math.min(c.transition_duration??.3,c.duration,prev.duration));if((c.transition||'none')==='none')c.transition='fade';}));
  }
  function importSrt(){const input=document.createElement('input');input.type='file';input.accept='.srt';input.onchange=async()=>{try{const text=await input.files[0].text(),clips=[],seconds=v=>{const [h,m,r]=v.replace(',','.').split(':');return Number(h)*3600+Number(m)*60+Number(r);};for(const block of text.replace(/\r/g,'').trim().split(/\n\s*\n/)){const lines=block.split('\n'),i=lines.findIndex(l=>l.includes('-->'));if(i<0)continue;const m=lines[i].match(/(\d+:\d+:\d+[,.]\d+)\s*-->\s*(\d+:\d+:\d+[,.]\d+)/);if(!m)continue;const start=seconds(m[1]),end=seconds(m[2]);if(end>start)clips.push({id:C.id(),start,duration:end-start,text:lines.slice(i+1).join('\n'),style:'classic',font_size:56,in:0,speed:1});}if(!clips.length)throw new Error('没有有效 SRT 字幕');edit(()=>tl().tracks.push({id:C.id(),name:'导入字幕',kind:'subtitle',clips}));}catch(e){msg(e.message);}};input.click();}
  async function recognize(){const {c}=find(s.selected);if(!c)return msg('先选择带声音的片段');try{await save();const job=await req(`projects/${s.p.id}/speech`,'POST',{revision:s.p.revision,timeline_id:s.tid,clip_id:c.id});
    const dialog=document.createElement('dialog');dialog.className='modal';dialog.innerHTML='<div class="modal-body"><h2>自动字幕识别</h2><p id="speechStatus">排队中，首次使用可能需要下载模型。</p><button class="button ghost" id="cancelSpeech">取消</button></div>';document.body.append(dialog);dialog.showModal();
    let stopped=false;const cancel=async()=>{stopped=true;await req(`speech/${job.id}/cancel`,'POST',{});dialog.close();};dialog.oncancel=e=>{e.preventDefault();cancel().catch(e=>msg(e.message));};dialog.querySelector('button').onclick=()=>cancel().catch(e=>msg(e.message));dialog.onclose=()=>dialog.remove();
    while(!stopped){await new Promise(r=>setTimeout(r,1800));const result=await req('speech/'+job.id);if(stopped)break;dialog.querySelector('p').textContent=result.status==='running'?'识别中，可继续等待或取消。':'排队中';
      if(['completed','failed','cancelled'].includes(result.status)){stopped=true;dialog.close();if(result.status==='failed')throw new Error(result.error);if(result.status==='completed'){if(!s.p||s.p.id!==job.project_id||!s.p.timelines.some(t=>t.id===job.timeline_id))return msg('项目已切换，请返回原项目重新识别');if(!result.segments.length)return msg('没有识别到语音');edit(()=>{const timeline=s.p.timelines.find(t=>t.id===job.timeline_id);timeline.tracks.push({id:C.id(),kind:'subtitle',name:'自动字幕',clips:result.segments.filter(r=>r.duration>=1/s.p.fps).map(r=>({...r,id:C.id(),in:0,speed:1,style:'classic',font_size:56}))});});msg('字幕已添加，请校对文字');}}}
  }catch(e){msg(e.message);}}
  function seek(t){s.playing=false;s.time=Math.max(0,Math.min(total(),t));for(const n of s.nodes.values())n.pause?.();}
  function play(){if(s.time>=total())s.time=0;s.playing=!s.playing;s.last=performance.now();}
  function node(c,a){if(s.nodes.has(c.id))return s.nodes.get(c.id);const n=document.createElement(a.kind==='image'?'img':a.kind==='audio'?'audio':'video');n.src=url(a);if(a.kind!=='image'){n.preload='auto';n.playsInline=true;n.onerror=()=>{s.playing=false;msg('素材无法预览，请转换为 H.264 MP4 或 WAV 后导入');};}s.nodes.set(c.id,n);return n;}
  function tick(now=performance.now()){
    if(!$('#editCanvas')||!location.hash.startsWith('#/editor/'))return;
    if(s.playing){s.time=Math.min(total(),s.time+Math.min(.1,(now-(s.last||now))/1000));if(s.time>=total())s.playing=false;}s.last=now;
    const canvas=$('#editCanvas'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,active=new Set();ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);
    const subtitle=[];
    for(const t of tl().tracks){if(t.hidden)continue;for(const c of [...t.clips].sort((a,b)=>a.start-b.start)){if(s.time<c.start||s.time>=C.end(c))continue;if(t.kind==='subtitle'){subtitle.push(c);continue;}const a=asset(c.asset_id);if(!a)continue;const n=node(c,a);active.add(c.id),localAudio(n,c,a,t);if(t.kind==='audio'||(a.kind!=='image'&&n.readyState<2)||(a.kind==='image'&&!n.complete))continue;drawMedia(ctx,n,a,c,w,h);}}
    const post=s.p.postprocess,overlays=[['pip_asset',post.pip_opacity,.8,.05,.18]];const sticker=asset(post.sticker_asset);if(sticker){const sw=Math.max(2,Math.floor(w*.2/2)*2),sh=sw*(sticker.height||h)/(sticker.width||w);for(const x of [(-sw+w*.02)/w,.98])for(const y of [(-sh+h*.02)/h,.98])overlays.push(['sticker_asset',1,x,y,.2]);}for(const [key,opacity,x,y,scale] of overlays)if(post[key]){const a=asset(post[key]);if(a){const c={id:'post-'+key+'-'+x+'-'+y,start:0,duration:total(),scale,x,y,opacity,loop:true},n=node(c,a);active.add(c.id);localAudio(n,c,a,{muted:true});if(a.kind==='image'?n.complete:n.readyState>=2)drawMedia(ctx,n,a,c,w,h);}}
    for(const c of subtitle)drawText(ctx,c,w,h);for(const [id,n] of s.nodes)if(!active.has(id))n.pause?.();
    if(post.progress){const reserved=s.reserved||(s.reserved=document.createElement('canvas'));if(reserved.width!==w)reserved.width=w;if(reserved.height!==h)reserved.height=h;reserved.getContext('2d').drawImage(canvas,0,0);ctx.clearRect(0,0,w,h);ctx.drawImage(reserved,0,0,w,h-6);ctx.fillStyle='#58d5b0';ctx.fillRect(0,h-6,w*s.time/(total()||1),6);}$('#editClock').textContent=time(s.time)+' / '+time(total());$('#editSeek').max=total()||1;$('#editSeek').value=s.time;const head=$('#editorPlayhead');if(head)head.style.left=150+s.time*s.zoom+'px';s.frame=requestAnimationFrame(tick);
  }
  function localAudio(n,c,a,t){if(a.kind==='image')return;const local=c.loop?s.time%(a.duration||1):(s.time-c.start)*(c.speed||1)+(c.in||0);n.playbackRate=c.speed||1;const age=s.time-c.start,fade=Math.min(1,c.fade_in?age/c.fade_in:1,c.fade_out?(c.duration-age)/c.fade_out:1);n.volume=Math.max(0,Math.min(1,(c.volume??1)*fade));n.muted=!!(t.muted||c.muted);if(n.readyState>=1&&Math.abs(n.currentTime-local)>(s.playing?.2:.025))n.currentTime=local;if(s.playing&&n.paused)n.play().catch(()=>{});else if(!s.playing&&!n.paused)n.pause();}
  function drawMedia(ctx,n,a,c,w,h){const scale=c.scale??1,full=scale===1&&!c.rotation;let dw=w*scale,dh=dw*(a.height||h)/(a.width||w),x=(c.x||0)*w,y=(c.y||0)*h;
    const age=s.time-c.start,td=c.transition_duration??.3;ctx.save();ctx.globalAlpha=(c.opacity??1)*((c.transition==='fade'&&td)?Math.min(1,age/td):1);ctx.filter={warm:'sepia(.2)',cool:'hue-rotate(10deg)',mono:'grayscale(1)',blur:'blur(3px)'}[c.effect]||'none';
    if(c.transition==='slide'&&td)x+=(w+dw)*Math.max(0,1-age/td);if(full){const r=Math.min(w/(a.width||w),h/(a.height||h));dw=(a.width||w)*r;dh=(a.height||h)*r;ctx.fillStyle='#000';ctx.fillRect(x,y,w,h);x+=(w-dw)/2;y+=(h-dh)/2;}
    if(c.transition==='wipe'&&td){ctx.beginPath();ctx.rect(x,y,dw*Math.min(1,age/td),dh);ctx.clip();}
    if(c.rotation){const r=c.rotation*Math.PI/180,bw=Math.abs(dw*Math.cos(r))+Math.abs(dh*Math.sin(r)),bh=Math.abs(dw*Math.sin(r))+Math.abs(dh*Math.cos(r));ctx.translate(x+bw/2,y+bh/2);ctx.rotate(r);x=-dw/2;y=-dh/2;}try{ctx.drawImage(n,x,y,dw,dh);}catch{}ctx.restore();}
  function drawText(ctx,c,w,h){const style=s.styles[c.style||'classic']||{},size=c.font_size||56;ctx.save();ctx.globalAlpha=c.opacity??1;ctx.font=`${style.bold?'bold ':''}${size}px "Microsoft YaHei","PingFang SC",sans-serif`;ctx.textAlign='center';ctx.textBaseline='bottom';const lines=[];for(const paragraph of (c.text||'').split('\n')){let line='';for(const ch of paragraph){if(ctx.measureText(line+ch).width>w-70){lines.push(line);line='';}line+=ch;}lines.push(line);}const x=w/2+(c.x||0)*w,y=h*.9+(c.y||0)*h;ctx.lineWidth=2*(style.outline||1);ctx.strokeStyle='#101010';if(style.box){ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(35,y-lines.length*size*1.2,w-70,lines.length*size*1.2+8);}let index=0;for(let i=0;i<lines.length;i++){const line=lines[i],yy=y-(lines.length-1-i)*size*1.2;if(c.style==='highlight'){let xx=x-ctx.measureText(line).width/2;ctx.textAlign='left';for(const ch of line){ctx.fillStyle=index/(c.text.length||1)<(s.time-c.start)/c.duration?'#ffff00':'#fff';ctx.strokeText(ch,xx,yy);ctx.fillText(ch,xx,yy);xx+=ctx.measureText(ch).width;index++;}}else{ctx.fillStyle=c.style==='yellow'?'#ffff00':'#fff';ctx.strokeText(line,x,yy);ctx.fillText(line,x,yy);}}ctx.restore();}
  async function poll(){clearTimeout(s.poll);if(!$('#exportList'))return;try{const d=await req('exports');$('#exportList').innerHTML='<h3>导出队列</h3>'+d.exports.map(j=>`<div class="editor-export-row"><b>${esc(j.title)}</b><span>${({queued:'排队中',running:'导出中',completed:'已完成',failed:'失败',cancelled:'已取消'})[j.status]} ${Math.round(j.progress)}%</span><small>${esc(j.error||j.output)}</small>${j.status==='completed'&&window.livecutDesktop?`<button data-reveal-export="${j.id}">打开文件位置</button>`:''}${['queued','running'].includes(j.status)?`<button data-cancel-export="${j.id}">取消</button>`:''}</div>`).join('');for(const b of document.querySelectorAll('[data-cancel-export]'))b.onclick=()=>req(`exports/${b.dataset.cancelExport}/cancel`,'POST',{}).then(poll).catch(e=>msg(e.message));for(const b of document.querySelectorAll('[data-reveal-export]'))b.onclick=()=>window.livecutDesktop.reveal(d.exports.find(j=>j.id===b.dataset.revealExport).output).catch(e=>msg(e.message));}catch(e){msg(e.message);}if(location.hash.startsWith('#/editor'))s.poll=setTimeout(poll,2000);}
  async function settings(root){const d=await req('settings');root.innerHTML=`<div class="hero"><div><h1>剪辑与导出</h1><p>独立编辑项目、输出位置和音频参数。</p></div></div><div class="panel"><form id="editorSettings" class="settings-form"><label>完成版目录<input name="output_dir" value="${esc(d.output_dir)}"></label><button type="button" class="button ghost" id="pickEditOutput">选择目录</button><label>音频码率<select name="audio_bitrate">${['128k','192k','256k','320k'].map(v=>`<option ${v===d.audio_bitrate?'selected':''}>${v}</option>`).join('')}</select><small>AAC · 44,100 Hz</small></label><label>字幕识别模型<input name="asr_model" value="${esc(d.asr_model)}"><small>默认 small，首次识别会下载模型；也可填写本地 faster-whisper 模型目录。</small></label><p>FFmpeg：${d.ffmpeg_available?'可用':'未找到'} · FFprobe：${d.ffprobe_available?'可用':'未找到'}</p><button class="button primary">保存</button></form></div>`;
    $('#pickEditOutput').onclick=async()=>{try{const r=window.livecutDesktop?await window.livecutDesktop.pickDirectory():await fetch('/api/files/pick',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"kind":"dir"}'}).then(r=>r.json());if(r.path)$('#editorSettings [name="output_dir"]').value=r.path;}catch(e){msg(e.message);}};
    $('#editorSettings').onsubmit=async e=>{e.preventDefault();try{await req('settings','PUT',Object.fromEntries(new FormData(e.target)));msg('已保存导出设置');}catch(e){msg(e.message);}};}
  async function mount(root){if(s.dirty)await save();cleanup();s.root=root;s.styles=(await req('settings')).subtitle_styles;const id=location.hash.split('/')[2];$('#pageCrumb').textContent='人工剪辑';for(const a of document.querySelectorAll('[data-nav]'))a.classList.toggle('active',a.dataset.nav==='editor');if(!id){s.p=null;return list(root);}s.p=await req('projects/'+id);s.tid=s.p.timelines[0].id;s.selected=null;s.undo=[];s.redo=[];s.time=0;s.dirty=false;layout();}
  window.addEventListener('keydown',e=>{if(!location.hash.startsWith('#/editor/')||e.target.matches('input,textarea,select')||e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey);}else if(e.code==='Space'){e.preventDefault();play();}else if(e.key.toLowerCase()==='s'&&!e.ctrlKey&&!e.metaKey)action('split');else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();action(e.shiftKey?'ripple':'delete');}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();seek(s.time+(e.key==='ArrowLeft'?-1:1)/s.p.fps);}});
  window.addEventListener('beforeunload',e=>{if(s.dirty){e.preventDefault();e.returnValue='';}});
  window.addEventListener('hashchange',()=>{if(!location.hash.startsWith('#/editor')){cleanup();if(s.dirty)save().catch(e=>msg(e.message));}});
  window.LiveCutEditor={mount,settings};
})();
